/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package processsaescritorio.vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import processsaescritorio.controlador.Lista;
import processsaescritorio.controlador.Registro;
import processsaescritorio.modelo.RolDTO;
import processsaescritorio.modelo.UnidadInternaDTO;
import processsaescritorio.modelo.UnidadInternaDAO;

/**
 *
 * @author yo
 */
public class ManejadorUnidadInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManejadorUnidadInterna
     */
    ArrayList<UnidadInternaDTO> listaUnidad;
    ArrayList<RolDTO> listaRol;
    int idGeneral;

    public ManejadorUnidadInterna() {
        initComponents();
        listarUnidadesInternas();
        listadoRoles();

    }

    public void resetearTabla() {
        listaUnidad.removeAll(listaUnidad);
        listarUnidadesInternas();
    }

    public void limpiarFormulario() {

        idGeneral = 0;
        tblUnidad.getSelectionModel().clearSelection();
        txtName.setText("");
        cbxRoles.setSelectedIndex(cbxRoles.getSelectedIndex());
        //arreglar estas dos
    }

    public void listarUnidadesInternas() {
        listaUnidad = new Lista().listarUnidadInterna();
        String[] columnas = {"ID", "Nombre", "Rol"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int filas, int columnas) {
                return false;
            }
        };
        for (UnidadInternaDTO unidad : listaUnidad) {
            String id = String.valueOf(unidad.getId());
            String name = String.valueOf(unidad.getNombre());
            String address = String.valueOf(unidad.getIdRol());
            Object[] elemento = {id, name, address};
            modeloTabla.addRow(elemento);
        };
        tblUnidad.setModel(modeloTabla);
    }

    public void listadoRoles() {

        for (RolDTO rol : new Lista().listarRol()) {
            //poner reglas de negocio
            cbxRoles.addItem(rol.getId() + "-" + rol.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnidad = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cbxRoles = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Manejador unidades internas");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        tblUnidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUnidadMouseClicked(evt);
            }
        });
        tblUnidad.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                tblUnidadComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(tblUnidad);

        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbxRoles.setMaximumRowCount(4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addComponent(cbxRoles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(326, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void tblUnidadComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblUnidadComponentResized
        tblUnidad.getColumnModel().getColumn(0).setResizable(false);
        tblUnidad.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblUnidad.getColumnModel().getColumn(1).setResizable(false);
        tblUnidad.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblUnidad.getColumnModel().getColumn(2).setResizable(false);
        tblUnidad.getColumnModel().getColumn(2).setPreferredWidth(10);
    }//GEN-LAST:event_tblUnidadComponentResized

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Grabar", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            try {

                String[] arrayRoles = cbxRoles.getSelectedItem().toString().split("-");
                int id_rol = Integer.parseInt(arrayRoles[0]);
                new Registro().registrarUnidadInterna(id_rol, txtName.getText());

                resetearTabla();
                limpiarFormulario();
                JOptionPane.showMessageDialog(null, "Grabado exitosamente.", "Grabar", JOptionPane.PLAIN_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingrese datos correspondientes", "Grabar", JOptionPane.PLAIN_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblUnidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUnidadMouseClicked
        int seleccion = tblUnidad.rowAtPoint(evt.getPoint());
        int id = Integer.parseInt(String.valueOf(tblUnidad.getValueAt(seleccion, 0)));

        idGeneral = id;
        //btnBorrar.setEnabled(true);

        UnidadInternaDTO unidad = new UnidadInternaDAO().UnidadPorID(id);
        txtName.setText(unidad.getNombre());

        new Lista().listarRoles().stream().filter((rol) -> (rol.getId() == unidad.getIdRol())).forEachOrdered((rol) -> {
            cbxRoles.setSelectedItem(rol.toString());
        });

    }//GEN-LAST:event_tblUnidadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxRoles;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUnidad;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
