/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package processsaescritorio.vista;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import processsaescritorio.modelo.UsuarioDTO;

/**
 *
 * @author Brayan
 */
public class VentanaPrincipal extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    private UsuarioDTO usuarioSesion;
    private Login ventanaPadre;

    /**
     * Creates new customizer VentanaPrincipal
     */
    public VentanaPrincipal(UsuarioDTO usuarioSesion, Login ventanaPadre) {
        initComponents();
        this.usuarioSesion = usuarioSesion;
        this.ventanaPadre = ventanaPadre;        
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
