//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSIGNED_UNIT
    {
        public ASSIGNED_UNIT()
        {
            this.ASSIGNED_UNIT1 = new HashSet<ASSIGNED_UNIT>();
            this.USER_INFO = new HashSet<USER_INFO>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_INTERNALUNIT { get; set; }
        public decimal ID_COMPANY { get; set; }
        public Nullable<decimal> ID_SUPERIOR_UNIT { get; set; }
    
        public virtual ICollection<ASSIGNED_UNIT> ASSIGNED_UNIT1 { get; set; }
        public virtual ASSIGNED_UNIT ASSIGNED_UNIT2 { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual INTERNAL_UNIT INTERNAL_UNIT { get; set; }
        public virtual ICollection<USER_INFO> USER_INFO { get; set; }
    }
}
