//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public COMPANY()
        {
            this.ASSIGNED_UNIT = new HashSet<ASSIGNED_UNIT>();
            this.USER_INFO = new HashSet<USER_INFO>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public byte[] LOGO { get; set; }
        public decimal ID_WORKING_AREA { get; set; }
        public decimal ID_COMMUNE { get; set; }
    
        public virtual ICollection<ASSIGNED_UNIT> ASSIGNED_UNIT { get; set; }
        public virtual COMMUNE COMMUNE { get; set; }
        public virtual WORKING_AREA WORKING_AREA { get; set; }
        public virtual ICollection<USER_INFO> USER_INFO { get; set; }
    }
}
