//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAY_OF_WEEK
    {
        public DAY_OF_WEEK()
        {
            this.LOOP_TASK_SCHEDULE = new HashSet<LOOP_TASK_SCHEDULE>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<LOOP_TASK_SCHEDULE> LOOP_TASK_SCHEDULE { get; set; }
    }
}
