//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERNAL_UNIT
    {
        public INTERNAL_UNIT()
        {
            this.ASSIGNED_UNIT = new HashSet<ASSIGNED_UNIT>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public decimal ID_ROLE { get; set; }
    
        public virtual ICollection<ASSIGNED_UNIT> ASSIGNED_UNIT { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
