//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSED_TASK
    {
        public PROCESSED_TASK()
        {
            this.PROCESSED_TASK_HISTORY = new HashSet<PROCESSED_TASK_HISTORY>();
        }
    
        public decimal ID { get; set; }
        public string COMMENTARY { get; set; }
        public System.DateTime ASSIGNATIONDATE { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public decimal ID_TASKSTATUS { get; set; }
        public decimal ID_TASK_ASSIGNMENT { get; set; }
        public Nullable<decimal> ID_SCHEDULED_LOOPTASK { get; set; }
    
        public virtual LOOP_TASK_SCHEDULE LOOP_TASK_SCHEDULE { get; set; }
        public virtual TASK_ASSIGNMENT TASK_ASSIGNMENT { get; set; }
        public virtual TASK_STATUS TASK_STATUS { get; set; }
        public virtual ICollection<PROCESSED_TASK_HISTORY> PROCESSED_TASK_HISTORY { get; set; }
    }
}
