//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProcessSAEntities : DbContext
    {
        public ProcessSAEntities()
            : base("name=ProcessSAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ASSIGNED_UNIT> ASSIGNED_UNIT { get; set; }
        public DbSet<COMMUNE> COMMUNE { get; set; }
        public DbSet<COMPANY> COMPANY { get; set; }
        public DbSet<DAY_OF_WEEK> DAY_OF_WEEK { get; set; }
        public DbSet<GENDER> GENDER { get; set; }
        public DbSet<INTERNAL_UNIT> INTERNAL_UNIT { get; set; }
        public DbSet<LOOP_TASK> LOOP_TASK { get; set; }
        public DbSet<LOOP_TASK_SCHEDULE> LOOP_TASK_SCHEDULE { get; set; }
        public DbSet<MONTH> MONTH { get; set; }
        public DbSet<PERMISSION> PERMISSION { get; set; }
        public DbSet<PROCESSED_TASK> PROCESSED_TASK { get; set; }
        public DbSet<PROCESSED_TASK_HISTORY> PROCESSED_TASK_HISTORY { get; set; }
        public DbSet<PROVINCE> PROVINCE { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<ROLE> ROLE { get; set; }
        public DbSet<TASK> TASK { get; set; }
        public DbSet<TASK_ASSIGNMENT> TASK_ASSIGNMENT { get; set; }
        public DbSet<TASK_STATUS> TASK_STATUS { get; set; }
        public DbSet<USER_INFO> USER_INFO { get; set; }
        public DbSet<WORKING_AREA> WORKING_AREA { get; set; }
    }
}
