//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSED_TASK_HISTORY
    {
        public decimal ID { get; set; }
        public decimal ID_ASSIGNEDTASK { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime EVENTDATETIME { get; set; }
        public string JUSTIFICATION { get; set; }
        public Nullable<decimal> ID_USERJUSTIFICATOR { get; set; }
    
        public virtual PROCESSED_TASK PROCESSED_TASK { get; set; }
        public virtual USER_INFO USER_INFO { get; set; }
    }
}
