//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINCE
    {
        public PROVINCE()
        {
            this.COMMUNE = new HashSet<COMMUNE>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public decimal ID_REGION { get; set; }
    
        public virtual ICollection<COMMUNE> COMMUNE { get; set; }
        public virtual REGION REGION { get; set; }
    }
}
