//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public ROLE()
        {
            this.INTERNAL_UNIT = new HashSet<INTERNAL_UNIT>();
            this.PERMISSION = new HashSet<PERMISSION>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<INTERNAL_UNIT> INTERNAL_UNIT { get; set; }
        public virtual ICollection<PERMISSION> PERMISSION { get; set; }
    }
}
