//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_ASSIGNMENT
    {
        public TASK_ASSIGNMENT()
        {
            this.LOOP_TASK = new HashSet<LOOP_TASK>();
            this.PROCESSED_TASK = new HashSet<PROCESSED_TASK>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_TASK { get; set; }
        public decimal ID_ASSIGNERUSER { get; set; }
        public Nullable<decimal> ID_RECEIVERUSER { get; set; }
    
        public virtual ICollection<LOOP_TASK> LOOP_TASK { get; set; }
        public virtual ICollection<PROCESSED_TASK> PROCESSED_TASK { get; set; }
        public virtual TASK TASK { get; set; }
        public virtual USER_INFO USER_INFO { get; set; }
        public virtual USER_INFO USER_INFO1 { get; set; }
    }
}
