//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        public TASK()
        {
            this.TASK_ASSIGNMENT = new HashSet<TASK_ASSIGNMENT>();
            this.TASK1 = new HashSet<TASK>();
            this.TASK11 = new HashSet<TASK>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string ISPREDEFINIDED { get; set; }
        public string ISACTIVE { get; set; }
        public Nullable<decimal> ID_SUPERIOR_TASK { get; set; }
        public Nullable<decimal> ID_DEPENDENT_TASK { get; set; }
    
        public virtual ICollection<TASK_ASSIGNMENT> TASK_ASSIGNMENT { get; set; }
        public virtual ICollection<TASK> TASK1 { get; set; }
        public virtual TASK TASK2 { get; set; }
        public virtual ICollection<TASK> TASK11 { get; set; }
        public virtual TASK TASK3 { get; set; }
    }
}
