//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INFO
    {
        public USER_INFO()
        {
            this.PROCESSED_TASK_HISTORY = new HashSet<PROCESSED_TASK_HISTORY>();
            this.TASK_ASSIGNMENT = new HashSet<TASK_ASSIGNMENT>();
            this.TASK_ASSIGNMENT1 = new HashSet<TASK_ASSIGNMENT>();
        }
    
        public decimal ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public System.DateTime BIRTHDATE { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public decimal ID_COMMUNE { get; set; }
        public decimal ID_ASSIGNED_UNIT { get; set; }
        public Nullable<decimal> ID_COMPANY { get; set; }
        public decimal ID_GENDER { get; set; }
    
        public virtual ASSIGNED_UNIT ASSIGNED_UNIT { get; set; }
        public virtual COMMUNE COMMUNE { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual GENDER GENDER { get; set; }
        public virtual ICollection<PROCESSED_TASK_HISTORY> PROCESSED_TASK_HISTORY { get; set; }
        public virtual ICollection<TASK_ASSIGNMENT> TASK_ASSIGNMENT { get; set; }
        public virtual ICollection<TASK_ASSIGNMENT> TASK_ASSIGNMENT1 { get; set; }
    }
}
