//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TASK_ASSOCIATED_TO_USER
    {
        public decimal IDSTATUS { get; set; }
        public decimal IDASSIGNERUSER { get; set; }
        public decimal IDRECEIVERUSER { get; set; }
        public System.DateTime Fecha_Asignacion { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public string Estado { get; set; }
        public string Nombre_Tarea { get; set; }
        public string Descripcion { get; set; }
        public string Asignado_Por { get; set; }
        public string Asignado_A { get; set; }
        public string Justificacion { get; set; }
    }
}
